export const siteSettingsQuery = `*[_type == "siteSettings"][0]`;
export const homePageQuery = `*[_type == "homePage"][0]`;
export const navigationQuery = `*[_type == "navigation"][0]`;
export const footerSettingsQuery = `*[_type == "footerSettings"][0]`;
export const announcementsQuery = `*[_type == "announcement"] | order(date desc)`;
export const newsArticlesQuery = `*[_type == "newsArticle"] | order(publishedDate desc)`;
export const staffQuery = `*[_type == "staff"] | order(order asc)`;
export const homepageStaffQuery = `*[_type == "staff" && showOnHomepage == true] | order(order asc)`;
export const unebResultsQuery = `*[_type == "unebResults"][0]`;
export const feeStructureQuery = `*[_type == "feeStructure"][0]`;
export const aboutContentQuery = `*[_type == "aboutContent"][0]`;
export const termDatesQuery = `*[_type == "termDates"][0]`;
export const whyChooseUsQuery = `*[_type == "whyChooseUs"][0]`;
export const contactPageQuery = `*[_type == "contactPage"][0]`;
export const admissionsContentQuery = `*[_type == "admissionsContent"][0]`;
export const galleryQuery = `*[_type == "galleryImage"] | order(dateTaken desc)`;
export const sportsQuery = `*[_type == "sport"] | order(name asc)`;
export const clubsQuery = `*[_type == "club"] | order(name asc)`;
export const subjectCategoriesQuery = `*[_type == "subjectCategory"] | order(order asc)`;
export const facilitiesQuery = `*[_type == "facility"]`;
export const singleNewsArticleQuery = (slug: string) => `*[_type == "newsArticle" && slug.current == "${slug}"][0]`;
export const singleStaffQuery = (slug: string) => `*[_type == "staff" && slug.current == "${slug}"][0]`;
export const singleSportQuery = (slug: string) => `*[_type == "sport" && slug.current == "${slug}"][0]`;
export const singleClubQuery = (slug: string) => `*[_type == "club" && slug.current == "${slug}"][0]`;
export const singlePageQuery = (slug: string) => `*[_type == "page" && slug.current == "${slug}"][0]`;